# Generated by Django 4.0.5 on 2022-06-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitob nomi kiriting', max_length=5000, verbose_name='Kitob nomini')),
                ('description', models.TextField(help_text='Kitob haqida qisqacha kiriting', verbose_name='Kitob haqida qisqacha')),
                ('author', models.CharField(help_text='Kitob muallifini kiriting', max_length=500, verbose_name='kitob muallifi')),
                ('image', models.ImageField(blank=True, help_text='Kitob rasmini kiriting', null=True, upload_to='book-images', verbose_name='Kitob rasmi')),
                ('file', models.FileField(help_text='Kitob faylini kiriting', upload_to='book-files', verbose_name='Kitob fayli')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.PositiveIntegerField(default=1, help_text='Yuklanganlar soni', verbose_name='Yuklanganlar soni')),
                ('viewed', models.PositiveIntegerField(default=1, help_text="Ko'rilganlar soni", verbose_name="Ko'rilganlar soni")),
                ('shared', models.PositiveIntegerField(default=1, help_text='Ulashilganlar soni', verbose_name='Ulashilganlar soni')),
            ],
            options={
                'verbose_name': 'Kitob ',
                'verbose_name_plural': 'Kitoblar ',
                'db_table': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Janr nomi kiriting', max_length=500, verbose_name='Janr nomini')),
            ],
            options={
                'verbose_name': 'Janr ',
                'verbose_name_plural': 'Janrlar ',
                'db_table': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Izoh yozing', verbose_name='Izoh')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.comments')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izohlar ',
                'db_table': 'Izohlar',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Kitob janr(lar)i ni kiriting', related_name='genres', to='books.genres', verbose_name='Kitob janr(lar)i'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(help_text='Kitob yuklagan shaxsni kiriting', on_delete=django.db.models.deletion.PROTECT, to='readers.kitobxon', verbose_name='Kitob yuklagan shaxs'),
        ),
    ]
