# Generated by Django 4.0.5 on 2022-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(help_text='Janr nomi kiriting', max_length=500, verbose_name='Janr nomi'),
        ),
    ]
