# Generated by Django 4.0.5 on 2022-06-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_genres_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Kitob yuklangan vaqt', verbose_name='Kitob yuklangan vaqt'),
        ),
    ]
