# Generated by Django 4.0.5 on 2022-06-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comments_writed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, help_text='Kitob audio fayli', null=True, upload_to='book-audios', verbose_name='Kitob audio fayli'),
        ),
    ]
