# Generated by Django 4.0.5 on 2022-06-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_genre_alter_comments_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Kitob janr(lar)i ni kiriting', related_name='janr', to='books.genres', verbose_name='Kitob janr(lar)i'),
        ),
    ]
