# Generated by Django 4.0.5 on 2022-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Kitob janr(lar)i ni kiriting', related_name='genres', to='books.genres', verbose_name='Kitob janr(lar)i'),
        ),
    ]
