# Generated by Django 4.0.5 on 2022-07-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Kitob janr(lar)i ni kiriting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.genres', verbose_name='Kitob janr(lar)i'),
        ),
    ]
