# Generated by Django 4.0.5 on 2022-07-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_janr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='janr',
        ),
    ]
