# Generated by Django 4.0.5 on 2022-06-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitobxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kitobxon', help_text='Kitobxon nomini kiriting', max_length=5000, verbose_name='Kitobxon nomi')),
                ('starred', models.PositiveIntegerField(default=0, help_text='Kitobxon statusini kiriting', verbose_name='kitobxon statusi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitobxon ',
                'verbose_name_plural': 'Kitobxonlar ',
                'db_table': 'Kitobxonlar',
            },
        ),
    ]
