# Generated by Django 4.0.5 on 2022-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='User ismi', max_length=1000, null=True, verbose_name='User ismi')),
                ('telegram_id', models.CharField(help_text='User Telegram Id si', max_length=400, verbose_name='Telegram ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, help_text='UUser username i', max_length=1000, null=True, verbose_name='User username i')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
                'db_table': 'Bot Users',
            },
        ),
    ]
