# Generated by Django 4.0.5 on 2022-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_botusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='telegram_id',
            field=models.IntegerField(help_text='User Telegram Id si', verbose_name='Telegram ID'),
        ),
    ]
